import type { ProjectDashboard } from "./page";

// TODO: Remove these fake demo data when the dashboard is ready to use only real backend data.
export const mockProjects: ProjectDashboard[] = [
  {
    id: 9001,
    name: "Robô Seguidor de Linha para Resgate",
    level: "Ensino Médio",
    participantName: "Ana Martins",
    institutionName: "Instituto Federal do Rio Grande do Sul",
    markedForReview: false,
    validated: true,
    createdAt: "2026-09-18T13:20:00",
    updatedAt: "2026-09-25T16:45:00",
  },
  {
    id: 9002,
    name: "Estação de Monitoramento Ambiental",
    level: "Ensino Técnico",
    participantName: "Lucas Ferreira",
    institutionName: "Escola Técnica Estadual Parobé",
    markedForReview: true,
    validated: false,
    createdAt: "2026-09-19T10:05:00",
    updatedAt: "2026-09-26T09:10:00",
  },
  {
    id: 9003,
    name: "Horta Automatizada com Arduino",
    level: "Ensino Fundamental",
    participantName: "Marina Costa",
    institutionName: "Colégio Municipal da Restinga",
    markedForReview: false,
    validated: false,
    createdAt: "2026-09-20T14:30:00",
    updatedAt: "2026-09-24T11:15:00",
  },
  {
    id: 9004,
    name: "Acessibilidade com Sensores de Proximidade",
    level: "Ensino Médio",
    participantName: "Rafael Souza",
    institutionName: "Instituto Estadual Rio Branco",
    markedForReview: false,
    validated: true,
    createdAt: "2026-09-16T08:40:00",
    updatedAt: "2026-09-23T17:20:00",
  },
  {
    id: 9005,
    name: "Coleta Seletiva Inteligente",
    level: "Ensino Técnico",
    participantName: "Beatriz Lima",
    institutionName: "Escola Técnica Estadual Senador Ernesto Dornelles",
    markedForReview: true,
    validated: false,
    createdAt: "2026-09-22T12:00:00",
    updatedAt: "2026-09-27T15:05:00",
  },
];
